### ISSUE TITLE
Realtime

### ISSUE THREAD

**Issue by sostenesapollo** [itsjustaplant/spofly#5]
Why the lirycs aren't updated in realtime on next spotify's song ?

**Comment by itsjustaplant** [comment]
spofly is integrated with [Spotify Web API](https://developer.spotify.com/documentation/web-api/). At that time i started to develop [spofly web](https://spoflyv1.herokuapp.com), i decided to not poll the API. But, now i can see that it was a bad call. I am currently implementing the feature to backend and soon it will be available for users. And also, you can build [spofly](https://github.com/itsjustaplant/spofly/tree/macos/spofly) app for macOS and Windows or you can download .dmg for macOS which has the auto-reload feature.
Stay with music.

**Comment by sostenesapollo** [comment]
Oh in electron app it works ? ^-^ that's fantastic !

**Comment by itsjustaplant** [comment]
I added another end point to check if the song is changed. I tested and it works _yay_  but it may fail. In the next days i'll review the logs and fix if there will be any bug. Thanks for creating an issue.
